### ISSUE TITLE
Nunchuk Adapter

### ISSUE THREAD

**Issue by uhi2000** [Jan--Henrik/hoverboard-breakout#5]
Hallo Jan,
besteht  die Möglichkeit, deinen Hoverboard Nunchuk Adapter kompl. bestückt käuflich zu erwerben???
Ich brauche sie für die Firmware-Transpotteer -Hack 2.1
Weil das Teil sehr amtlich aussieht.....und vieleicht später noch einige mehr???
Gruß
Tim

**Comment by Jan--Henrik** [comment]
Hi,
ich habe ein Paar Bausätze, welche ich gegen eine Spende abgeben kann. Du kannst mir am besten eine mail schicken: janhenrik(at)janhenrik.org

**Comment by uhi2000** [comment]
hi,
super für deine schnelle Info .Ich werde dir in den nächsten Tagen eine E-mail schicken.
Kurze Frage noch . Ich bin dabei für meine Oma einen fahrbaren Stuhl zu bauen für in der Wohnung.Sie ist nicht mehr so gut auf den Beinen.
Und das mit dem Nunchuk wäre für meine Oma das ideale Steuer- Element.
Ich habe das Mainboard mit Niklas firmware-transpotter -hack 2.1 geflasht..
ich hoffe ich liege damit richtig ?Das einige was noch zu ändern wäre ist die hohe Geschwindigkeit.
Das ist zu schnell für in der Wohnung und glaube ich auch für ältere Leute.
wie könnte ich den max.Speed am besten Drosseln bzw. noch eine zusätzliche Bremsfunktion mit einbauen ???könnte ich auch einen 5Volt Hall-Joystick anstelle des Nunchuks anschliesen?? Ein Tipp wäre cool von dir....
Gruß im voraus...Tim

**Comment by uhi2000** [comment]
Hi Jan,
super für deine schnelle Info.Ich werde dir in den nächsten Tagen nochmal eine E-mail schicken bezüglich der Platinen.
Kurze Frage noch . Ich bin dabei für meine Oma einen fahrbaren Stuhl zu bauen für in der Wohnung. Sie ist nicht mehr so gut auf den Beinen.
Und das mit dem Nunchuk, wäre für meine Oma denke ich das ideale Steuer- Element.
Ich habe das Mainboard mit Niklas firmware-transpotter -hack 2.1 geflasht..Blicke noch nicht bei den ganzen Firmwares von euch durch sorry,
ich hoffe ich liege mit dieser Version richtig ?Das einige was noch zu ändern wäre ist die hohe Geschwindigkeit.
Das ist zu schnell für in der Wohnung und glaube ich auch für ältere Leute.
wie könnte ich den max.Speed am besten Drosseln bzw. noch eine zusätzliche Bremsfunktion mit einbauen für den Nachlauf ???
Könnte ich auch einen 5Volt Hall-Joystick anstelle des Nunchuk anschließen?? Ein Tipp wäre cool von dir....
Gruß
Tim

**Comment by Jan--Henrik** [comment]
Hi, eine Mail hast du mir noch nicht geschickt?
Das Fahrverhalten kannst du in src/main.c verändern, über die config.h wird nur die Hardware konfiguriert. Du kannst auch einen Analogen Joystick verweden, jedoch solltest du beachten, dass die maximale Eingangsspannung 3.3V ist. Ebenso müsstest du dann die config.h so wie die src/main.c ebenfalls anpassen.
"Blicke noch nicht bei den ganzen Firmwares von euch durch sorry," Wir haben nur eine Firmware und haben zu dem Projekt "TranspOtter" ein Release gemacht.
