### ISSUE TITLE
What are JP1 and JP2 for?

### ISSUE THREAD

**Issue by thankthemaker** [Jan--Henrik/hoverboard-breakout#7]
Hi,

can you explain, what the two jumpers JP1 and JP2 are used for in the hoverboard-breakout?
I looked for some documentation of the schematic, but I can't find any.

Thanks!
David

**Comment by zanderknight** [comment]
Hello I am not a person who can answer these questions. I haven't touched a
hoverboard in a while sorry.

**Comment by Jan--Henrik** [comment]
Hey @thankthemaker, JP1 and JP2 are used to either connect two hoverboards in parallel (e.g. for ADC operation) or to create a crossover to have them communicate via UART

**Comment by thankthemaker** [comment]
Hi @Jan--Henrik ,
thanks a lot! Makes things much clearer and maybe helpful for others too.
If you don't mind, I'll update your Readme and send you a merge request.
David

**Comment by Jan--Henrik** [comment]
Please do!
